Waiting for workflow to finish

diff --git a/.github/actions/dispatch-and-download/action.yml b/.github/actions/dispatch-and-download/action.yml
--- a/.github/actions/dispatch-and-download/action.yml
+++ b/.github/actions/dispatch-and-download/action.yml
@@ -54,6 +54,40 @@ runs:
       run: |
         echo ${{steps.return_dispatch.outputs.run_id}}
         echo ${{steps.return_dispatch.outputs.run_url}}
+    - name: Wait for workflow to finish
+      shell: bash
+      run: |
+        sleep 5
+
+        timeout="30" # in seconds
+        interval="10" # in seconds
+        counter=0
+        timeout_counter=0
+        url="https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/actions/runs/${{steps.return_dispatch.outputs.run_id}}"
+        while true; do
+          run_data=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ inputs.token }}" $url)
+          status=$(echo "$run_data" | jq -r '.status')
+
+          echo "Try -> $timeout_counter; status -> $status"
+          if [ "$status" = "completed" ]; then
+            conclusion=$(echo "$run_data" | jq -r '.conclusion')
+            if [ "$conclusion" != "success" ]; then
+              echo "::error::The workflow has not completed successfully."
+              exit 1
+            else
+              echo "::notice::The workflow completed successfully!"
+              break
+            fi
+          fi
+
+          timeout_counter=$((timeout_counter + 1))
+          if [ $((timeout_counter * interval)) -ge $((timeout * 60)) ]; then
+            echo "::error::Timeout waiting for the workflow to complete."
+            exit 1
+          fi
+
+          sleep $interval
+        done
 
     - name: Download all artifacts
       uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
