Fix get artifact name

diff --git a/.github/workflows/_build-any.yml b/.github/workflows/_build-any.yml
--- a/.github/workflows/_build-any.yml
+++ b/.github/workflows/_build-any.yml
@@ -180,6 +180,7 @@ jobs:
         run: |
           ./Scripts/build.sh $_BUILD_PROJECT_PATH $_BUILD_SCHEME $_BUILD_MODE
 
+      #TODO: consider transitioning this back to a workflow script instead now that we have env vars
       - name: Prepare artifacts for upload to GitHub
         run: |
           mkdir -p $_EXPORT_PATH
@@ -193,8 +194,20 @@ jobs:
       - name: Get artifact name
         id: get_artifact_name
         run: |
-          ARTIFACT_NAME=$(bundle exec fastlane get_artifact_name --env $_BW_ENV | grep "artifact_filename: " | cut -d' ' -f3)
-          echo "🧱 Artifact name: $ARTIFACT_NAME"
+          ARTIFACT_NAME=$(bundle exec fastlane get_artifact_name \
+            --env $_BW_ENV \
+            build_mode:$_BUILD_MODE \
+            version_name:$_VERSION_NAME \
+            version_number:$_VERSION_NUMBER \
+            xcode_version:$_XCODE_VERSION \
+            | grep "artifact_filename: " \
+            | cut -d' ' -f3)
+
+          if [ -z "$ARTIFACT_NAME" ]; then
+            echo "::error::Failed to get artifact name"
+            exit 1
+          fi
+
           echo "filename=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
 
       - name: Upload artifacts to GitHub
