[PM-22524]  GitHub Release workflow supports releasing BWPM and BWA (#1654)

diff --git a/.github/workflows/github-release.yml b/.github/workflows/github-release.yml
--- a/.github/workflows/github-release.yml
+++ b/.github/workflows/github-release.yml
@@ -7,29 +7,7 @@ on:
         description: 'GitHub Action Run ID containing artifacts'
         required: true
         type: string
-      version-name:
-        description: 'Version Name Override - E.g. "2024.11.1"'
-        required: true
-        type: string
-      version-number:
-        description: 'Version Number Override - E.g. "123456"'
-        required: true
-        type: string
-      draft:
-        description: 'Create as draft release'
-        type: boolean
-        default: true
-      prerelease:
-        description: 'Mark as pre-release'
-        type: boolean
-        default: true
-      branch-protection-type:
-        description: 'Branch protection type'
-        type: choice
-        options:
-          - Branch Name
-          - GitHub API
-        default: Branch Name
+
 env:
     ARTIFACTS_PATH: artifacts
 jobs:
@@ -51,36 +29,34 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           ARTIFACT_RUN_ID: ${{ inputs.artifact-run-id }}
-          BRANCH_PROTECTION_TYPE: ${{ inputs.branch-protection-type }}
         run: |
-          release_branch=$(gh run view $ARTIFACT_RUN_ID --json headBranch -q .headBranch)
+          workflow_data=$(gh run view $ARTIFACT_RUN_ID --json headBranch,workflowName)
+          release_branch=$(echo "$workflow_data" | jq -r .headBranch)
+          workflow_name=$(echo "$workflow_data" | jq -r .workflowName)
 
-          case "$BRANCH_PROTECTION_TYPE" in
-            "Branch Name")
-              if [[ "$release_branch" != "main" && ! "$release_branch" =~ ^release/ ]]; then
-                echo "::error::Branch '$release_branch' is not 'main' or a release branch starting with 'release/'. Releases must be created from protected branches."
-                exit 1
-              fi
+          # branch protection check
+          if [[ "$release_branch" != "main" && ! "$release_branch" =~ ^release/ ]]; then
+            echo "::error::Branch '$release_branch' is not 'main' or a release branch starting with 'release/'. Releases must be created from protected branches."
+            exit 1
+          fi
+
+          echo "release_branch=$release_branch" >> $GITHUB_OUTPUT
+          echo "workflow_name=$workflow_name" >> $GITHUB_OUTPUT
+
+          case "$workflow_name" in
+            *"Password Manager"* | "Build" | "CI - main")
+              echo "app_name=Password Manager" >> $GITHUB_OUTPUT
+              echo "app_name_suffix=bwpm" >> $GITHUB_OUTPUT
               ;;
-            "GitHub API")
-              #NOTE requires token with "administration:read" scope
-              if ! gh api "repos/${{ github.repository }}/branches/$release_branch/protection" | grep -q "required_status_checks"; then
-                echo "::error::Branch '$release_branch' is not protected. Releases must be created from protected branches. If that's not correct, confirm if the github token user has the 'administration:read' scope."
-                exit 1
-              fi
+            *"Authenticator"*)
+              echo "app_name=Authenticator" >> $GITHUB_OUTPUT
+              echo "app_name_suffix=bwa" >> $GITHUB_OUTPUT
               ;;
             *)
-              echo "::error::Unsupported branch protection type: $BRANCH_PROTECTION_TYPE"
+              echo "::error::Unknown workflow name: $workflow_name"
               exit 1
               ;;
           esac
-
-          echo "release_branch=$release_branch" >> $GITHUB_OUTPUT
-      - name: Get last release tag
-        id: get_last_tag
-        run: |
-          last_release_id=$(git tag -l --sort=-authordate | head -n 1)
-          echo "last_release_id=$last_release_id" >> $GITHUB_OUTPUT
 
       - name: Download artifacts
         env:
@@ -88,65 +64,72 @@ jobs:
           ARTIFACT_RUN_ID: ${{ inputs.artifact-run-id }}
         run: ./Scripts/download-artifacts.sh $ARTIFACTS_PATH $ARTIFACT_RUN_ID
 
-      - name: Parse version info
+      - name: Parse version info from run logs and set release tag name
+        id: get_release_info
         env:
-          _VERSION_NAME: ${{ inputs.version-name }}
-          _VERSION_NUMBER: ${{ inputs.version-number }}
-        id: version_info
+          _APP_NAME_SUFFIX: ${{ steps.get_release_branch.outputs.app_name_suffix }}
         run: |
-          if [ ! -f ARTIFACTS_PATH/version_info.zip ]; then
-            echo "::warning::version-version.zip not found. Confirm why the build workflow skipped uploading it."
-
-            version_name="$_VERSION_NAME"
-            version_number="$_VERSION_NUMBER"
-            if [[ -z "$_VERSION_NAME" ]]; then
-              echo "::warning::version name override input is empty. Using default value."
-              version_name="0.0.0"
-            fi
-
-            if [[ -z "$_VERSION_NUMBER" ]]; then
-              echo "::warning::version number override input is empty. Using default value."
-              version_number="0"
-            fi
-
-            echo "version_number=$version_number" >> $GITHUB_OUTPUT
-            echo "version_name=$version_name" >> $GITHUB_OUTPUT
-            echo "Version: $version_name ($version_number)"
-            exit 0
+          if [ -f "$ARTIFACTS_PATH/version-info.zip" ]; then
+            echo "🔖 version-info.zip was found, extracting info"
+            unzip -o "$ARTIFACTS_PATH/version-info.zip" -d "tmp"
+            filepath="tmp/version-info/version_info.json"
+            version_name=$(jq -r '.version_name' "$filepath")
+            version_number=$(jq -r '.version_number' "$filepath")
+            rm -rf tmp
+            rm "$ARTIFACTS_PATH/version-info.zip"
+          else
+            echo "::warning::version-info.zip not found. Confirm why the build workflow skipped uploading it. Using default values - 0.0.0 (0)"
+            version_name="0.0.0"
+            version_number="0"
           fi
 
-          # version-info.zip was found, extracting info
-          unzip -o "$ARTIFACTS_PATH/version-info.zip" -d "tmp"
-          filepath="tmp/version-info/version_info.json"
-          version_name=$(jq -r '.version_name' "$filepath")
-          version_number=$(jq -r '.version_number' "$filepath")
           echo "version_number=$version_number" >> $GITHUB_OUTPUT
           echo "version_name=$version_name" >> $GITHUB_OUTPUT
-          rm -rf tmp
+          echo "🔖 Version: $version_name ($version_number)"
+
+          tag_name="v$version_name-$_APP_NAME_SUFFIX" # e.g. v2025.6.0-bwpm
+          echo "🔖 New tag name: $tag_name"
+          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
+
+          last_release_tag=$(git tag -l --sort=-authordate | grep "$_APP_NAME_SUFFIX" | head -n 1)
+          echo "🔖 Last release tag: $last_release_tag"
+          echo "last_release_tag=$last_release_tag" >> $GITHUB_OUTPUT
 
       - name: Create GitHub Release
         id: create_release
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          _APP_NAME: ${{ steps.get_release_branch.outputs.app_name }}
+          _RELEASE_BRANCH: ${{ steps.get_release_branch.outputs.release_branch }}
+          _VERSION_NAME: ${{ steps.get_release_info.outputs.version_name }}
+          _VERSION_NUMBER: ${{ steps.get_release_info.outputs.version_number }}
+          _TAG_NAME: ${{ steps.get_release_info.outputs.tag_name }}
+          _LAST_RELEASE_TAG: ${{ steps.get_release_info.outputs.last_release_tag }}
         run: |
-          # Create release with generated notes
-          url=$(gh release create "v${{ steps.version_info.outputs.version_name }}" \
-            --title "${{ steps.version_info.outputs.version_name }} (${{ steps.version_info.outputs.version_number }})" \
-            --target ${{ steps.get_release_branch.outputs.release_branch }} \
+          echo "⌛️ Creating release for $_APP_NAME $_VERSION_NAME ($_VERSION_NUMBER) on $_RELEASE_BRANCH"
+          release_url=$(gh release create "$_TAG_NAME" \
+            --title "$_APP_NAME $_VERSION_NAME ($_VERSION_NUMBER)" \
+            --target $_RELEASE_BRANCH \
             --generate-notes \
-            --notes-start-tag "${{ steps.get_last_tag.outputs.last_release_id }}" \
-            --prerelease=${{ inputs.prerelease }} \
-            --draft=${{ inputs.draft }} \
+            --notes-start-tag "$_LAST_RELEASE_TAG" \
+            --draft \
             $ARTIFACTS_PATH/*)
+
           # Extract release tag from URL
-          release_id=$(echo "$url" | sed 's/.*\/tag\///')
-          echo "release_id=$release_id" >> $GITHUB_OUTPUT
+          release_id_from_url=$(echo "$release_url" | sed 's/.*\/tag\///')
+          echo "release_id_from_url=$release_id_from_url" >> $GITHUB_OUTPUT
+
+          echo "url=$release_url" >> $GITHUB_OUTPUT
+
+          echo "✅ Release created: $release_url"
+          echo "🔖 Release ID from URL: $release_id_from_url"
+          echo "🔖 Release URL: $release_url"
 
       - name: Update Release Description
         id: update_release_description
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          RELEASE_ID: ${{ steps.create_release.outputs.release_id }}
+          RELEASE_ID: ${{ steps.create_release.outputs.release_id_from_url }}
           ARTIFACT_RUN_ID: ${{ inputs.artifact-run-id }}
         run: |
           # Add builds source to the end of the release description
@@ -157,31 +140,31 @@ jobs:
 
           # draft release links change after editing
           echo "release_url=$new_url" >> $GITHUB_OUTPUT
+          echo "🔖 New Release URL: $new_url"
 
       - name: Add Release Summary
         env:
-          RELEASE_ID: ${{ steps.create_release.outputs.release_id }}
-          RELEASE_TAG: "v${{ steps.version_info.outputs.version_name }}"
-          RELEASE_BRANCH: ${{ steps.get_release_branch.outputs.release_branch }}
-          LAST_RELEASE_TAG: ${{ steps.get_last_tag.outputs.last_release_id }}
-          RELEASE_URL: ${{ steps.update_release_description.outputs.release_url }}
-          VERSION_NAME: ${{ steps.version_info.outputs.version_name }}
-          VERSION_NUMBER: ${{ steps.version_info.outputs.version_number }}
+          _RELEASE_TAG: ${{ steps.get_release_info.outputs.tag_name }}
+          _RELEASE_BRANCH: ${{ steps.get_release_branch.outputs.release_branch }}
+          _LAST_RELEASE_TAG: ${{ steps.get_release_info.outputs.last_release_tag }}
+          _RELEASE_URL: ${{ steps.update_release_description.outputs.release_url }}
+          _VERSION_NAME: ${{ steps.get_release_info.outputs.version_name }}
+          _VERSION_NUMBER: ${{ steps.get_release_info.outputs.version_number }}
         run: |
           echo "# :fish_cake: Release ready at:" >> $GITHUB_STEP_SUMMARY
-          echo "$RELEASE_URL" >> $GITHUB_STEP_SUMMARY
+          echo "$_RELEASE_URL" >> $GITHUB_STEP_SUMMARY
           echo "" >> $GITHUB_STEP_SUMMARY
 
-          if [[ "$VERSION_NAME" == "0.0.0" || "$VERSION_NUMBER" == "0" ]]; then
+          if [[ "$_VERSION_NAME" == "0.0.0" || "$_VERSION_NUMBER" == "0" ]]; then
             echo "> [!CAUTION]" >> $GITHUB_STEP_SUMMARY
             echo "> Version name or number wasn't previously found and a default value was used. You'll need to manually update the release Title, Tag and Description, specifically, the "Full Changelog" link." >> $GITHUB_STEP_SUMMARY
             echo "" >> $GITHUB_STEP_SUMMARY
           fi
 
           echo ":clipboard: Confirm that the defined GitHub Release options are correct:"  >> $GITHUB_STEP_SUMMARY
-          echo " * :bookmark: New tag name: \`$RELEASE_TAG\`" >> $GITHUB_STEP_SUMMARY
-          echo " * :palm_tree: Target branch: \`$RELEASE_BRANCH\`" >> $GITHUB_STEP_SUMMARY
-          echo " * :ocean: Previous tag set in the description \"Full Changelog\" link: \`$LAST_RELEASE_TAG\`" >> $GITHUB_STEP_SUMMARY
+          echo " * :bookmark: New tag name: \`$_RELEASE_TAG\`" >> $GITHUB_STEP_SUMMARY
+          echo " * :palm_tree: Target branch: \`$_RELEASE_BRANCH\`" >> $GITHUB_STEP_SUMMARY
+          echo " * :ocean: Previous tag set in the description \"Full Changelog\" link: \`$_LAST_RELEASE_TAG\`" >> $GITHUB_STEP_SUMMARY
           echo " * :white_check_mark: Description has automated release notes and they match the commits in the release branch" >> $GITHUB_STEP_SUMMARY
           echo "> [!NOTE]" >> $GITHUB_STEP_SUMMARY
           echo "> Commits directly pushed to branches without a Pull Request won't appear in the automated release notes." >> $GITHUB_STEP_SUMMARY
