Detect downgrades

diff --git a/.github/workflows/sdlc-sdk-update.yml b/.github/workflows/sdlc-sdk-update.yml
--- a/.github/workflows/sdlc-sdk-update.yml
+++ b/.github/workflows/sdlc-sdk-update.yml
@@ -146,6 +146,28 @@ jobs:
           echo "sdk-swift-ref=$SDK_SWIFT_REF" >> $GITHUB_OUTPUT
           echo "sdk-internal-ref=$SDK_INTERNAL_REF" >> $GITHUB_OUTPUT
 
+      - name: Detect downgrade and prevent updating to the current version
+        id: detect-downgrade
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
+          _CURRENT_SDK_SWIFT_REF: ${{ steps.get-current-sdk.outputs.sdk-swift-ref }}
+          _NEW_SDK_SWIFT_REF: ${{ inputs.sdk-swift-ref }}
+        run: |
+          if [ "$_CURRENT_SDK_SWIFT_REF" = "$_NEW_SDK_SWIFT_REF" ]; then
+            echo "::error::Provided sdk-swift ref is the same as the current version in main."
+            exit 1
+          fi
+
+          COMPARE_RESULT=$(gh api "repos/bitwarden/sdk-swift/compare/$_CURRENT_SDK_SWIFT_REF...$_NEW_SDK_SWIFT_REF" --jq '.status')
+
+          if [ "$COMPARE_RESULT" = "behind" ]; then
+            echo "::warning::The new SDK version ($_NEW_SDK_SWIFT_REF) is older than the current version ($_CURRENT_SDK_SWIFT_REF)"
+            echo "downgrading=true" >> $GITHUB_OUTPUT
+          else
+            echo "✅ New SDK version is newer - proceeding with update"
+            echo "downgrading=false" >> $GITHUB_OUTPUT
+          fi
+
       - name: Update SDK Version
         env:
           _SDK_VERSION: ${{ inputs.sdk-version }}
@@ -177,14 +199,17 @@ jobs:
           _NEW_SDK_SWIFT_REF: ${{ inputs.sdk-swift-ref }}
           _OLD_SDK_SWIFT_REF: ${{ steps.get-current-sdk.outputs.sdk-swift-ref }}
           _OLD_SDK_INTERNAL_REF: ${{ steps.get-current-sdk.outputs.sdk-internal-ref }}
+          _DOWNGRADING: ${{ steps.detect-downgrade.outputs.downgrading }}
         run: |
           _NEW_SDK_INTERNAL_REF=$(echo "$_NEW_SDK_VERSION" | cut -d'-' -f3-)
-          CHANGELOG=$(./Scripts/get-repo-changelog.sh "bitwarden/sdk-internal" "$_OLD_SDK_INTERNAL_REF" "$_NEW_SDK_INTERNAL_REF")
-          PR_BODY="Updates the SDK from \`$_OLD_SDK_SWIFT_REF\` to \`$_NEW_SDK_SWIFT_REF\`
+          PR_BODY="Updates the SDK from \`$_OLD_SDK_SWIFT_REF\` to \`$_NEW_SDK_SWIFT_REF\`"
 
-          ## What's Changed
-
-          $CHANGELOG"
+          if [ "$_DOWNGRADING" = "true" ]; then
+            PR_BODY="$PR_BODY\n\n##:warning: Downgrading SDK to an older version. :warning:"
+          else
+            CHANGELOG=$(./Scripts/get-repo-changelog.sh "bitwarden/sdk-internal" "$_OLD_SDK_INTERNAL_REF" "$_NEW_SDK_INTERNAL_REF")
+            PR_BODY="$PR_BODY\n\n## What's Changed\n\n$CHANGELOG"
+          fi
 
           EXISTING_PR=$(gh pr list --head $_BRANCH_NAME --base main --state open --json number --jq '.[0].number // empty')
           _NEW_SDK_SWIFT_REF_SHORT="${_NEW_SDK_SWIFT_REF:0:7}"
